orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  kustomize: finc/kustomize@0.0.2
  kustomize-orb: soenergy/kustomize-orb@0.0.2
version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        environment:
          app: "onurs-test-app"
jobs:
  my-job-name: 
    executor: my-custom-executor
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - kustomize/install
      - gcp-cli/install:
          version: '369.0.0'
      - gcp-cli/initialize:
          gcloud-service-key: service_account 
          google-project-id: project_id
      - run: gcloud projects list
      - run: gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export PATH=/bin/bash:$PATH' >> $BASH_ENV
            echo 'export timestamp=$(date +%Y%m%d%H%M%S)' >> $BASH_ENV
            echo 'export tag=2.0.1' >> $BASH_ENV
            echo 'export fullimagetag=$app:$tag' >> $BASH_ENV
            source $BASH_ENV
            echo $fullimagetag
      - checkout
      - run: docker --version
      # - run: docker build . -t europe-west2-docker.pkg.dev/onur-tola-sandbox/dummy-repo/onur-test-image -f Dockerfile
      - run: docker build . -t my-app
      - run: docker tag my-app europe-west2-docker.pkg.dev/onur-tola-sandbox/dummy-repo/$fullimagetag
      # - run: docker build . -t europe-west2-docker.pkg.dev/onur-tola-sandbox/dummy-repo/$fullimagetag -f Dockerfile 
      - run: docker images
      - run: docker push europe-west2-docker.pkg.dev/onur-tola-sandbox/dummy-repo/$fullimagetag
      - kustomize-orb/submit:
          dl-plateng-deployment-branch: "faster-switching-test"
          kustomize-file-location: "config/envs/test"
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name